<?php

//$res = array(
//    'code' => 0, 'msg' => '', 'data' => array(
//        0 => array(
//            'id' => 91270, 'data' => array(
//                0    => array(
//                    'id'                        => 0, 'app_id' => 'apppcHqlTPT3482',
//                    'resource_id'               => 'i_5f8c038260b2f3cc6b367797', 'tag_id' => 506223, 'tag_name' => '课程分类',
//                    'title'                     => '内部课', 'summary' => '',
//                    'img_url'                   => 'http://wechatapppro-1252524126.file.myqcloud.com/apppcHqlTPT3482/image/kgdd5b4f01n00m8iehhlh.jpg',
//                    'img_url_compressed'        => 'http://wechatapppro-1252524126.file.myqcloud.com/apppcHqlTPT3482/image/compress/414320304kgdd5b4f01n00m8iehhlh.jpg',
//                    'img_url_compressed_larger' => 'http://wechatapppro-1252524126.file.myqcloud.com/apppcHqlTPT3482/image/compress/640480927kgdd5b4f01n00m8iehhlh.jpg',
//                    'alive_img_url'             => '', 'payment_type' => 1, 'price' => 0, 'line_price' => '0.00',
//                    'start_at'                  => '2020-10-18 16:57:37', 'stop_at' => '2038-01-19 03:14:07', 'state' => 0,
//                    'type'                      => 1, 'recycle_state' => 0, 'period' => 0, 'sell_mode' => 0,
//                    'product_name'              => '', 'view_count' => '0', 'comment_count' => '0', 'resource_count' => 0,
//                    'feeds_count'               => 0, 'order_weight' => 0, 'content_app_id' => '', 'finished_state' => 0,
//                    'resource_created'          => '2020-10-18 16:57:39', 'zb_stop_at' => null,
//                    'zb_start_at'               => '2020-10-18 16:58:10', 'manual_stop_at' => null, 'is_stop_sell' => 0,
//                    'created_at'                => '2020-10-18 16:57:39', 'updated_at' => '2020-12-10 20:27:49',
//                    'alive_type'                => 0, 'act_type' => 0, 'sub_type' => 0, 'show_price' => '',
//                    'in_activity'               => 0, 'marketing_tag' => array(), 'resource_tag' => array(),
//                ), 1 => array(
//                    'id'                        => 874, 'app_id' => 'apppcHqlTPT3482',
//                    'resource_id'               => 'p_5f8af5f060b2f3cc6b36778d', 'tag_id' => 506223, 'tag_name' => '课程分类',
//                    'title'                     => '萨法', 'summary' => '范德萨',
//                    'img_url'                   => 'http://wechatapppro-1252524126.file.myqcloud.com/apppcHqlTPT3482/image/kgdd5b4f01n00m8iehhlh.jpg',
//                    'img_url_compressed'        => 'http://wechatapppro-1252524126.file.myqcloud.com/apppcHqlTPT3482/image/compress/414320304kgdd5b4f01n00m8iehhlh.jpg',
//                    'img_url_compressed_larger' => 'http://wechatapppro-1252524126.file.myqcloud.com/apppcHqlTPT3482/image/compress/640480927kgdd5b4f01n00m8iehhlh.jpg',
//                    'alive_img_url'             => '', 'payment_type' => 1, 'price' => 0, 'line_price' => '0.00',
//                    'start_at'                  => '2020-10-18 16:52:09', 'stop_at' => '2038-01-19 03:14:07', 'state' => 0,
//                    'type'                      => 6, 'recycle_state' => 0, 'period' => 0, 'sell_mode' => 0,
//                    'product_name'              => '', 'view_count' => 0, 'comment_count' => 0, 'resource_count' => '3',
//                    'feeds_count'               => 0, 'order_weight' => 1, 'content_app_id' => '', 'finished_state' => 0,
//                    'resource_created'          => '2020-10-17 21:47:29', 'zb_stop_at' => null,
//                    'zb_start_at'               => '2020-10-18 16:52:09', 'manual_stop_at' => null, 'is_stop_sell' => 0,
//                    'created_at'                => '2020-10-17 21:47:29', 'updated_at' => '2020-12-10 20:27:49',
//                    'alive_type'                => 0, 'act_type' => 0, 'sub_type' => 0, 'show_price' => '',
//                    'in_activity'               => 0, 'marketing_tag' => array(), 'purchase_count' => '0',
//                    'resource_tag'              => array(),
//                ), 2 => array(
//                    'id'                        => 875, 'app_id' => 'apppcHqlTPT3482',
//                    'resource_id'               => 'p_5f8af4cf60b2f3cc6b36778c', 'tag_id' => 506223, 'tag_name' => '课程分类',
//                    'title'                     => '1111111111111111111111111111', 'summary' => '111111111111111111',
//                    'img_url'                   => 'http://wechatapppro-1252524126.file.myqcloud.com/apppcHqlTPT3482/image/kgal7ra30i7u4147fg2j.jpg',
//                    'img_url_compressed'        => 'http://wechatapppro-1252524126.file.myqcloud.com/apppcHqlTPT3482/image/compress/414320732kgal7ra30i7u4147fg2j.jpg',
//                    'img_url_compressed_larger' => 'http://wechatapppro-1252524126.file.myqcloud.com/apppcHqlTPT3482/image/compress/640480927kgal7ra30i7u4147fg2j.jpg',
//                    'alive_img_url'             => '', 'payment_type' => 1, 'price' => 0, 'line_price' => '0.00',
//                    'start_at'                  => '2020-10-18 16:52:09', 'stop_at' => '2038-01-19 03:14:07', 'state' => 0,
//                    'type'                      => 6, 'recycle_state' => 0, 'period' => 0, 'sell_mode' => 0,
//                    'product_name'              => '', 'view_count' => 0, 'comment_count' => 0, 'resource_count' => '3',
//                    'feeds_count'               => 0, 'order_weight' => 2, 'content_app_id' => '', 'finished_state' => 0,
//                    'resource_created'          => '2020-10-17 21:42:40', 'zb_stop_at' => null,
//                    'zb_start_at'               => '2020-10-18 16:52:09', 'manual_stop_at' => null, 'is_stop_sell' => 0,
//                    'created_at'                => '2020-10-17 21:42:40', 'updated_at' => '2020-12-10 20:27:49',
//                    'alive_type'                => 0, 'act_type' => 0, 'sub_type' => 0, 'show_price' => '',
//                    'in_activity'               => 0, 'marketing_tag' => array(), 'purchase_count' => '0',
//                    'resource_tag'              => array(),
//                ), 3 => array(
//                    'id'                        => 876, 'app_id' => 'apppcHqlTPT3482',
//                    'resource_id'               => 'p_5f896ba360b2f3cc6b367769', 'tag_id' => 506223, 'tag_name' => '课程分类',
//                    'title'                     => '1026消息中心专栏', 'summary' => '1026消息中心专栏',
//                    'img_url'                   => 'http://wechatapppro-1252524126.file.myqcloud.com/apppcHqlTPT3482/image/kg7erg3802lmzdedze7d.jpg',
//                    'img_url_compressed'        => 'http://wechatapppro-1252524126.file.myqcloud.com/apppcHqlTPT3482/image/compress/414320777kg7erg3802lmzdedze7d.jpg',
//                    'img_url_compressed_larger' => 'http://wechatapppro-1252524126.file.myqcloud.com/apppcHqlTPT3482/image/compress/640480464kg7erg3802lmzdedze7d.jpg',
//                    'alive_img_url'             => '', 'payment_type' => 2, 'price' => 1, 'line_price' => '0.00',
//                    'start_at'                  => '2020-10-18 16:52:09', 'stop_at' => '2038-01-19 03:14:07', 'state' => 0,
//                    'type'                      => 6, 'recycle_state' => 0, 'period' => 0, 'sell_mode' => 0,
//                    'product_name'              => '', 'view_count' => 0, 'comment_count' => 0, 'resource_count' => '2',
//                    'feeds_count'               => 0, 'order_weight' => 3, 'content_app_id' => '', 'finished_state' => 0,
//                    'resource_created'          => '2020-10-16 17:45:08', 'zb_stop_at' => null,
//                    'zb_start_at'               => '2020-10-18 16:52:09', 'manual_stop_at' => null, 'is_stop_sell' => 0,
//                    'created_at'                => '2020-10-16 17:45:08', 'updated_at' => '2020-12-10 20:27:49',
//                    'alive_type'                => 0, 'act_type' => 0, 'sub_type' => 0, 'show_price' => '0.01',
//                    'in_activity'               => 0, 'marketing_tag' => array(), 'repertory_id' => '',
//                    'purchase_count'            => '4', 'resource_tag' => array(),
//                ), 4 => array(
//                    'id'                        => 877, 'app_id' => 'apppcHqlTPT3482',
//                    'resource_id'               => 'p_5f89630660b2f3cc6b367761', 'tag_id' => 506223, 'tag_name' => '课程分类',
//                    'title'                     => 'kyo-dev-column-1',
//                    'summary'                   => 'kyo-dev-column-1kyo-dev-column-1kyo-dev-column-1kyo-dev-column-1kyo-dev-column-1kyo-dev-column-1kyo-dev-column-1kyo-dev-column-1kyo-dev-column-1kyo-dev-column-1kyo-dev-column-1kyo-dev-column-1kyo-dev-column-1kyo-dev-column-1kyo-dev-column-1kyo-dev-column-1',
//                    'img_url'                   => 'http://wechatapppro-1252524126.file.myqcloud.com/apppcHqlTPT3482/image/kga9tl2o0wf2cexjl9rd.jpg',
//                    'img_url_compressed'        => 'http://wechatapppro-1252524126.file.myqcloud.com/apppcHqlTPT3482/image/compress/414320180kga9tl2o0wf2cexjl9rd.jpg',
//                    'img_url_compressed_larger' => 'http://wechatapppro-1252524126.file.myqcloud.com/apppcHqlTPT3482/image/compress/640480985kga9tl2o0wf2cexjl9rd.jpg',
//                    'alive_img_url'             => '', 'payment_type' => 1, 'price' => 0, 'line_price' => '0.00',
//                    'start_at'                  => '2020-10-18 16:52:09', 'stop_at' => '2038-01-19 03:14:07', 'state' => 0,
//                    'type'                      => 6, 'recycle_state' => 0, 'period' => 0, 'sell_mode' => 0,
//                    'product_name'              => '', 'view_count' => 0, 'comment_count' => 0, 'resource_count' => '1',
//                    'feeds_count'               => 0, 'order_weight' => 4, 'content_app_id' => '', 'finished_state' => 0,
//                    'resource_created'          => '2020-10-16 17:08:22', 'zb_stop_at' => null,
//                    'zb_start_at'               => '2020-10-18 16:52:09', 'manual_stop_at' => null, 'is_stop_sell' => 0,
//                    'created_at'                => '2020-10-16 17:08:22', 'updated_at' => '2020-12-10 20:27:49',
//                    'alive_type'                => 0, 'act_type' => 0, 'sub_type' => 0, 'show_price' => '',
//                    'in_activity'               => 0, 'marketing_tag' => array(), 'purchase_count' => '0',
//                    'resource_tag'              => array(),
//                ), 5 => array(
//                    'id'                        => 878, 'app_id' => 'apppcHqlTPT3482',
//                    'resource_id'               => 'p_5f87d26860b2f3cc6b3676fa', 'tag_id' => 506223, 'tag_name' => '课程分类',
//                    'title'                     => 'ddsdds', 'summary' => 'fdfddfff',
//                    'img_url'                   => 'http://wechatapppro-1252524126.file.myqcloud.com/apppcHqlTPT3482/image/kga9xlig0zsxai63zj9.jpg',
//                    'img_url_compressed'        => 'http://wechatapppro-1252524126.file.myqcloud.com/apppcHqlTPT3482/image/compress/414320559kga9xlig0zsxai63zj9.jpg',
//                    'img_url_compressed_larger' => 'http://wechatapppro-1252524126.file.myqcloud.com/apppcHqlTPT3482/image/compress/640480511kga9xlig0zsxai63zj9.jpg',
//                    'alive_img_url'             => '', 'payment_type' => 1, 'price' => 0, 'line_price' => '0.00',
//                    'start_at'                  => '2020-10-18 16:52:09', 'stop_at' => '2038-01-19 03:14:07', 'state' => 0,
//                    'type'                      => 6, 'recycle_state' => 0, 'period' => 0, 'sell_mode' => 0,
//                    'product_name'              => '', 'view_count' => 0, 'comment_count' => 0, 'resource_count' => '16',
//                    'feeds_count'               => 0, 'order_weight' => 5, 'content_app_id' => '', 'finished_state' => 0,
//                    'resource_created'          => '2020-10-15 12:39:06', 'zb_stop_at' => null,
//                    'zb_start_at'               => '2020-10-18 16:52:09', 'manual_stop_at' => null, 'is_stop_sell' => 0,
//                    'created_at'                => '2020-10-15 12:39:06', 'updated_at' => '2020-12-10 20:27:49',
//                    'alive_type'                => 0, 'act_type' => 0, 'sub_type' => 0, 'show_price' => '',
//                    'in_activity'               => 0, 'marketing_tag' => array(), 'purchase_count' => '0',
//                    'resource_tag'              => array(),
//                ),
//            ),
//        ),
//    ),
//);

//$res = array_unique($res['data'][0]['data'], SORT_REGULAR);

$res = '[
                {
                    "id":0,
                    "app_id":"appdpulgxmb1662",
                    "resource_id":"term_5fb31fe66619f_9XpdRZ",
                    "tag_id":4313638,
                    "tag_name":"分类导航",
                    "title":"第2期新营销训练营乘风班",
                    "summary":"新营销训练营乘风班，给你批量裂变、团队增员的秘籍！",
                    "img_url":"http://wechatapppro-1252524126.file.myqcloud.com/appdpulgxmb1662/image/kgj3iysj0lmdu0thhcv.jpg",
                    "img_url_compressed":"http://wechatapppro-1252524126.file.myqcloud.com/appdpulgxmb1662/image/compress/414320769kgj3iysj0lmdu0thhcv.jpg",
                    "img_url_compressed_larger":"http://wechatapppro-1252524126.file.myqcloud.com/appdpulgxmb1662/image/compress/640480225kgj3iysj0lmdu0thhcv.jpg",
                    "alive_img_url":"",
                    "payment_type":2,
                    "price":9900,
                    "line_price":"0.00",
                    "start_at":"2020-12-08 13:53:48",
                    "stop_at":"2038-01-19 03:14:07",
                    "state":0,
                    "type":25,
                    "recycle_state":0,
                    "period":0,
                    "sell_mode":0,
                    "product_name":"",
                    "view_count":0,
                    "comment_count":0,
                    "resource_count":0,
                    "feeds_count":0,
                    "order_weight":1,
                    "content_app_id":"",
                    "finished_state":0,
                    "resource_created":"2020-12-08 17:43:56",
                    "zb_stop_at":"2020-11-24 22:00:00",
                    "zb_start_at":"2020-11-18 18:30:00",
                    "manual_stop_at":null,
                    "is_stop_sell":0,
                    "created_at":"2020-12-08 17:43:56",
                    "updated_at":"2020-12-09 10:47:04",
                    "alive_type":0,
                    "act_type":0,
                    "sub_type":0,
                    "show_price":"99",
                    "in_activity":0,
                    "marketing_tag":[

                    ],
                    "repertory_id":"",
                    "join_count":"0",
                    "resource_tag":[

                    ]
                },
                {
                    "id":0,
                    "app_id":"appdpulgxmb1662",
                    "resource_id":"term_5fb31fe66619f_9XpdRZ",
                    "tag_id":4313638,
                    "tag_name":"分类导航",
                    "title":"第2期新营销训练营乘风班",
                    "summary":"新营销训练营乘风班，给你批量裂变、团队增员的秘籍！",
                    "img_url":"http://wechatapppro-1252524126.file.myqcloud.com/appdpulgxmb1662/image/kgj3iysj0lmdu0thhcv.jpg",
                    "img_url_compressed":"http://wechatapppro-1252524126.file.myqcloud.com/appdpulgxmb1662/image/compress/414320769kgj3iysj0lmdu0thhcv.jpg",
                    "img_url_compressed_larger":"http://wechatapppro-1252524126.file.myqcloud.com/appdpulgxmb1662/image/compress/640480225kgj3iysj0lmdu0thhcv.jpg",
                    "alive_img_url":"",
                    "payment_type":2,
                    "price":9900,
                    "line_price":"0.00",
                    "start_at":"2020-12-08 13:53:48",
                    "stop_at":"2038-01-19 03:14:07",
                    "state":0,
                    "type":25,
                    "recycle_state":0,
                    "period":0,
                    "sell_mode":0,
                    "product_name":"",
                    "view_count":0,
                    "comment_count":0,
                    "resource_count":0,
                    "feeds_count":0,
                    "order_weight":1,
                    "content_app_id":"",
                    "finished_state":0,
                    "resource_created":"2020-12-08 17:43:56",
                    "zb_stop_at":"2020-11-24 22:00:00",
                    "zb_start_at":"2020-11-18 18:30:00",
                    "manual_stop_at":null,
                    "is_stop_sell":0,
                    "created_at":"2020-12-08 17:43:56",
                    "updated_at":"2020-12-09 10:47:04",
                    "alive_type":0,
                    "act_type":0,
                    "sub_type":0,
                    "show_price":"99",
                    "in_activity":0,
                    "marketing_tag":[

                    ],
                    "repertory_id":"",
                    "join_count":"0",
                    "resource_tag":[

                    ]
                },
                {
                    "id":0,
                    "app_id":"appdpulgxmb1662",
                    "resource_id":"term_5fb31fe66619f_9XpdRZ",
                    "tag_id":4313638,
                    "tag_name":"分类导航",
                    "title":"第2期新营销训练营乘风班",
                    "summary":"新营销训练营乘风班，给你批量裂变、团队增员的秘籍！",
                    "img_url":"http://wechatapppro-1252524126.file.myqcloud.com/appdpulgxmb1662/image/kgj3iysj0lmdu0thhcv.jpg",
                    "img_url_compressed":"http://wechatapppro-1252524126.file.myqcloud.com/appdpulgxmb1662/image/compress/414320769kgj3iysj0lmdu0thhcv.jpg",
                    "img_url_compressed_larger":"http://wechatapppro-1252524126.file.myqcloud.com/appdpulgxmb1662/image/compress/640480225kgj3iysj0lmdu0thhcv.jpg",
                    "alive_img_url":"",
                    "payment_type":2,
                    "price":9900,
                    "line_price":"0.00",
                    "start_at":"2020-12-08 13:53:48",
                    "stop_at":"2038-01-19 03:14:07",
                    "state":0,
                    "type":25,
                    "recycle_state":0,
                    "period":0,
                    "sell_mode":0,
                    "product_name":"",
                    "view_count":0,
                    "comment_count":0,
                    "resource_count":0,
                    "feeds_count":0,
                    "order_weight":1,
                    "content_app_id":"",
                    "finished_state":0,
                    "resource_created":"2020-12-08 17:43:56",
                    "zb_stop_at":"2020-11-24 22:00:00",
                    "zb_start_at":"2020-11-18 18:30:00",
                    "manual_stop_at":null,
                    "is_stop_sell":0,
                    "created_at":"2020-12-08 17:43:56",
                    "updated_at":"2020-12-09 10:47:04",
                    "alive_type":0,
                    "act_type":0,
                    "sub_type":0,
                    "show_price":"99",
                    "in_activity":0,
                    "marketing_tag":[

                    ],
                    "repertory_id":"",
                    "join_count":"0",
                    "resource_tag":[

                    ]
                },
                {
                    "id":0,
                    "app_id":"appdpulgxmb1662",
                    "resource_id":"term_5f8ea43fe616b_CfgXgO",
                    "tag_id":4313638,
                    "tag_name":"分类导航",
                    "title":"新营销训练营乘风班第1期",
                    "summary":"新营销训练营乘风班，给你批量裂变、团队增员的秘籍！",
                    "img_url":"http://wechatapppro-1252524126.file.myqcloud.com/appdpulgxmb1662/image/kgj3iysj0lmdu0thhcv.jpg",
                    "img_url_compressed":"http://wechatapppro-1252524126.file.myqcloud.com/appdpulgxmb1662/image/compress/414320769kgj3iysj0lmdu0thhcv.jpg",
                    "img_url_compressed_larger":"http://wechatapppro-1252524126.file.myqcloud.com/appdpulgxmb1662/image/compress/640480225kgj3iysj0lmdu0thhcv.jpg",
                    "alive_img_url":"",
                    "payment_type":2,
                    "price":9900,
                    "line_price":"0.00",
                    "start_at":"2020-12-08 13:54:00",
                    "stop_at":"2038-01-19 03:14:07",
                    "state":0,
                    "type":25,
                    "recycle_state":0,
                    "period":0,
                    "sell_mode":0,
                    "product_name":"",
                    "view_count":0,
                    "comment_count":0,
                    "resource_count":0,
                    "feeds_count":0,
                    "order_weight":2,
                    "content_app_id":"",
                    "finished_state":0,
                    "resource_created":"2020-12-08 17:44:59",
                    "zb_stop_at":"2020-11-02 22:55:00",
                    "zb_start_at":"2020-10-26 16:30:00",
                    "manual_stop_at":null,
                    "is_stop_sell":0,
                    "created_at":"2020-12-08 17:44:59",
                    "updated_at":"2020-12-09 10:47:04",
                    "alive_type":0,
                    "act_type":0,
                    "sub_type":0,
                    "show_price":"99",
                    "in_activity":0,
                    "marketing_tag":[

                    ],
                    "repertory_id":"",
                    "join_count":"0",
                    "resource_tag":[

                    ]
                },
                {
                    "id":0,
                    "app_id":"appdpulgxmb1662",
                    "resource_id":"term_5f8ea43fe616b_CfgXgO",
                    "tag_id":4313638,
                    "tag_name":"分类导航",
                    "title":"新营销训练营乘风班第1期",
                    "summary":"新营销训练营乘风班，给你批量裂变、团队增员的秘籍！",
                    "img_url":"http://wechatapppro-1252524126.file.myqcloud.com/appdpulgxmb1662/image/kgj3iysj0lmdu0thhcv.jpg",
                    "img_url_compressed":"http://wechatapppro-1252524126.file.myqcloud.com/appdpulgxmb1662/image/compress/414320769kgj3iysj0lmdu0thhcv.jpg",
                    "img_url_compressed_larger":"http://wechatapppro-1252524126.file.myqcloud.com/appdpulgxmb1662/image/compress/640480225kgj3iysj0lmdu0thhcv.jpg",
                    "alive_img_url":"",
                    "payment_type":2,
                    "price":9900,
                    "line_price":"0.00",
                    "start_at":"2020-12-08 13:54:00",
                    "stop_at":"2038-01-19 03:14:07",
                    "state":0,
                    "type":25,
                    "recycle_state":0,
                    "period":0,
                    "sell_mode":0,
                    "product_name":"",
                    "view_count":0,
                    "comment_count":0,
                    "resource_count":0,
                    "feeds_count":0,
                    "order_weight":2,
                    "content_app_id":"",
                    "finished_state":0,
                    "resource_created":"2020-12-08 17:44:59",
                    "zb_stop_at":"2020-11-02 22:55:00",
                    "zb_start_at":"2020-10-26 16:30:00",
                    "manual_stop_at":null,
                    "is_stop_sell":0,
                    "created_at":"2020-12-08 17:44:59",
                    "updated_at":"2020-12-09 10:47:04",
                    "alive_type":0,
                    "act_type":0,
                    "sub_type":0,
                    "show_price":"99",
                    "in_activity":0,
                    "marketing_tag":[

                    ],
                    "repertory_id":"",
                    "join_count":"0",
                    "resource_tag":[

                    ]
                },
                {
                    "id":0,
                    "app_id":"appdpulgxmb1662",
                    "resource_id":"term_5f8ea43fe616b_CfgXgO",
                    "tag_id":4313638,
                    "tag_name":"分类导航",
                    "title":"新营销训练营乘风班第1期",
                    "summary":"新营销训练营乘风班，给你批量裂变、团队增员的秘籍！",
                    "img_url":"http://wechatapppro-1252524126.file.myqcloud.com/appdpulgxmb1662/image/kgj3iysj0lmdu0thhcv.jpg",
                    "img_url_compressed":"http://wechatapppro-1252524126.file.myqcloud.com/appdpulgxmb1662/image/compress/414320769kgj3iysj0lmdu0thhcv.jpg",
                    "img_url_compressed_larger":"http://wechatapppro-1252524126.file.myqcloud.com/appdpulgxmb1662/image/compress/640480225kgj3iysj0lmdu0thhcv.jpg",
                    "alive_img_url":"",
                    "payment_type":2,
                    "price":9900,
                    "line_price":"0.00",
                    "start_at":"2020-12-08 13:54:00",
                    "stop_at":"2038-01-19 03:14:07",
                    "state":0,
                    "type":25,
                    "recycle_state":0,
                    "period":0,
                    "sell_mode":0,
                    "product_name":"",
                    "view_count":0,
                    "comment_count":0,
                    "resource_count":0,
                    "feeds_count":0,
                    "order_weight":2,
                    "content_app_id":"",
                    "finished_state":0,
                    "resource_created":"2020-12-08 17:44:59",
                    "zb_stop_at":"2020-11-02 22:55:00",
                    "zb_start_at":"2020-10-26 16:30:00",
                    "manual_stop_at":null,
                    "is_stop_sell":0,
                    "created_at":"2020-12-08 17:44:59",
                    "updated_at":"2020-12-09 10:47:04",
                    "alive_type":0,
                    "act_type":0,
                    "sub_type":0,
                    "show_price":"99",
                    "in_activity":0,
                    "marketing_tag":[

                    ],
                    "repertory_id":"",
                    "join_count":"0",
                    "resource_tag":[

                    ]
                }
            ]';
$res = json_decode($res,true);
$res = array_unique($res, SORT_REGULAR);
print_r($res);exit;
